<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Scalex.Core.Portable\**" />
    <EmbeddedResource Remove="Scalex.Core.Portable\**" />
    <None Remove="Scalex.Core.Portable\**" />
  </ItemGroup>

</Project>